### ISSUE TITLE
Consider time_of_day class

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/clock#152]
- Considered to be a calendar type
- Variable precision from hour -> nanosecond
- `time_of_day(hour, minute = NULL, second = NULL, subsecond = NULL, ..., subsecond_precision = NULL)`
- `get_*()` and `set_*()` methods
- No `add_*()` methods because I think wrap around arithmetic would just be confusing
- Comparison methods `>`, `<`, and equality `==` (if we had these, this is more reason not to have arithmetic, because wrap around arithmetic would conflict with comparision ops. in this way it works opposite of the weekday type which has circular arithmetic but no comparison ops)
- Consider that names would go on the `hour` field
- Can convert from time points, calendars, POSIXct, and durations as long as they have hour precision (consider what happens when converting from a duration goes out of the "conventional range")
- Can support parsing with custom template that returns the C++ hh_mm_ss object. Similar impl to ymd parser. Has a precision argument.
- Formatting could assume the day is 1970-01-01, and then give full `format` power.
- No way to go back to calendar / tp through an `as_*()` method.
- But we would have `as_duration()`. Then you can do `tp + as_duration(tod)`
- `calendar_group/narrow/widen()` all make sense
- Conversion to duration + duration-floor + conversion back is nice for rounding by things like 200 seconds

**Comment by DavisVaughan** [comment]
See bullet 5 of Wording to note why they call it hh_mm_as not time-of-day. And for why they allow negative and for values outside the standard range http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1466r3.html

**Comment by DavisVaughan** [comment]
I'm going to leave this out of clock for now, and we can revisit if there is an extreme need for it, since {hms} already exists

**Comment by eitsupi** [comment]
It would be useful to have a time type in nanoseconds so that the time64 type present in Apache Arrow can be converted to R.
https://github.com/apache/arrow/blob/508eb2f26f0aa0b35f4c1223b496a2a8e58a93dd/format/Schema.fbs#L258-L275

While hms is sufficient for most applications, there are some differences, such as negative times and times after 24:00 are not supported by Arrow.
