### ISSUE TITLE
Compatibility with data.table (see vignette)

### ISSUE THREAD

**Issue by tjtnew** [r-lib/clock#154]
Do you mind keeping an issue open re: compatibility with **{data.table}** (summarised in the [FAQ vignette](https://r-lib.github.io/clock/articles/faq.html#why-doesn-t-this-work-with-data-table-))?  Also are you aware if there is any relevant issue open their end that could be linked (I've seen multiple discussions re POSIXlt but could not find anything obvious about record types more generally).  

I'm currently implementing a lot of s3 classes for year-weeks, year-months, year-quarters and think it would be better to rely **{clock}** but unfortunately I'm using data.table for the speed up it brings so hoping something eventually works out 🤞

**Comment by DavisVaughan** [comment]
I've added an issue explaining the general concept of record types to data.table's repo. I'd prefer not to have outstanding issues that are related to something that I don't think clock can solve, so I'm going to close this one https://github.com/Rdatatable/data.table/issues/4910
