### ISSUE TITLE
The dplyr "gather" command will not work with any dates formatted using the clock library

### ISSUE THREAD

**Issue by claritabonita** [r-lib/clock#289]
I have a list of dates, some start and end times.
I tried to convert them to long format and when implementing the gather command, it immediately aborts and exits R. Once I convert them to POSIXct format, then it works.
This occurred with the dates in naive format and also in zoned format.

**Comment by DavisVaughan** [comment]
You are right that `gather()` definitely doesn't work with clock types. In general, it doesn't seem to work with the rcrd types from vctrs, which makes sense because the C++ code that `gather()` uses was never meant to support them.

Luckily `pivot_longer()` does work, and is backed by infrastructure that supports a much wider range of generic types, so I'd encourage you to use that instead.

``` r
library(tidyr)
library(clock)

df <- tibble(
  x = naive_time_parse(c("2019-01-01T00:00:00.1234", "2019-01-02T00:00:00.1234"), precision = "microsecond"),
  y = naive_time_parse(c("2019-01-03T00:00:00.1234", "2019-01-04T00:00:00.1234"), precision = "microsecond"),
)

df
#> # A tibble: 2 × 2
#>   x                          y                         
#>   <tp<naive><micro>>         <tp<naive><micro>>        
#> 1 2019-01-01T00:00:00.123400 2019-01-03T00:00:00.123400
#> 2 2019-01-02T00:00:00.123400 2019-01-04T00:00:00.123400

xx <- gather(df, "key", "value", x, y)
xx
#> # A tibble: 4 × 2
#>   key   value                     
#>   <chr> <tp<naive><micro>>        
#> 1 x     2019-01-01T00:00:00.017899
#> 2 x     2019-01-02T00:00:00.017900
#> 3 y     2019-01-01T00:00:00.017899
#> 4 y     2019-01-02T00:00:00.017900

unclass(xx)
#> $key
#> [1] "x" "x" "y" "y"
#> 
#> $value
#> <time_point<naive><microsecond>[2]>
#> [1] "2019-01-01T00:00:00.017899" "2019-01-02T00:00:00.017900"
#> 
#> attr(,"row.names")
#> [1] 1 2 3 4

pivot_longer(df, c(x, y))
#> # A tibble: 4 × 2
#>   name  value                     
#>   <chr> <tp<naive><micro>>        
#> 1 x     2019-01-01T00:00:00.123400
#> 2 y     2019-01-03T00:00:00.123400
#> 3 x     2019-01-02T00:00:00.123400
#> 4 y     2019-01-04T00:00:00.123400
```

<sup>Created on 2022-02-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
> dates, some start and end times

Also, depending on what you are doing, you might be interested in this package I am working on https://github.com/DavisVaughan/iv. It is still extremely experimental, but you may find it interesting https://davisvaughan.github.io/iv/articles/iv.html

**Comment by claritabonita** [comment]
Ok, thank you! I was able to work around by using gather with the POSIXct and then converting to naive format after. I'm not sure if there is any problem with that......... Good to know that pivot_longer works with these types and is being superceded.
