### ISSUE TITLE
date_time_build not erroring as documented

### ISSUE THREAD

**Issue by TimTaylor** [r-lib/clock#293]
In the documentation for `date_time_build()` we have (emphasis mine)
> Note that clock always assumes that R's Date class is naive, so converting a Date to a POSIXct will always attempt to retain the printed year, month, and day. **_Where possible, the resulting time will be at midnight (00:00:00), but in some rare cases this is not possible due to daylight saving time. If that issue ever arises, an error will be thrown_**, which can be resolved by explicitly supplying nonexistent or ambiguous.

This works 
``` r
as.Date("2039-04-03") |> clock::as_date_time(zone="NZ", nonexistent="error", ambiguous="error")
#> [1] "2039-04-03 NZDT"
```
but I'd expect the following to error
``` r
as.Date("2039-04-04") |> clock::as_date_time(zone="NZ", nonexistent="error", ambiguous="error")
#> [1] "2039-04-04 01:00:00 NZDT"
```

I suspect this is related to something which changes in R formatting in 2039 (see #292 which I closed as began to suspect that was an R not clock issue).

**Comment by TimTaylor** [comment]
Apologies - closing this as well. This seems to be an issue only in Ubuntu 18.04, not latest Fedora or MacOS so suspect it's something to do with system libraries.

**Comment by DavisVaughan** [comment]
Yea to confirm, this returns the right result on my Mac, so I suppose it may just be some kind of printing but on Ubuntu

``` r
as.Date("2039-04-04") |> clock::as_date_time(zone="NZ", nonexistent="error", ambiguous="error")
#> [1] "2039-04-04 NZST"
```

<sup>Created on 2022-02-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
