### ISSUE TITLE
Use of `...` incorrectly forbidden

### ISSUE THREAD

**Issue by wurli** [r-lib/clock#307]
I noticed a small issue with `date_format()` and `as_zoned_time()` where the use of `...` is actually required, but is forbidden in the documentation.

**Comment by DavisVaughan** [comment]
I see how that could be confusing but I think I prefer the documentation as it is now for simplicity.

On the help page of the generic, the dots are technically passed on to methods, but I never think of the generic as what is actually "called", I think of the method as being what you call

<img width="732" alt="Screen Shot 2022-11-12 at 8 58 12 AM" src="https://user-images.githubusercontent.com/19150088/201477520-bf709102-920a-4e4c-a096-002df074ec2b.png">

On the help page of the method after you click through by clicking the `dates (Date)` link above, the dots really must be empty

<img width="708" alt="Screen Shot 2022-11-12 at 8 58 47 AM" src="https://user-images.githubusercontent.com/19150088/201477637-34af758e-960f-4680-942d-d431ee175339.png">

This is the case for every generic/method combination that I have in clock, I really do force the `...` to be empty in every method to enforce named optional arguments, so I feel like this inconsistency is ok to get users used to the idea that the dots are typically empty
