### ISSUE TITLE
install fails with 'UTC' is not a known time zone

### ISSUE THREAD

**Issue by james74901** [r-lib/clock#334]
Not sure where to go with this. Compile seems fine, but then I get the following:

** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘clock’:
 .onLoad failed in loadNamespace() for 'clock', details:
  call: zone_validate(zone)
  error: 'UTC' is not a known time zone.
Error: loading failed
Execution halted
ERROR: loading failed

> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Amazon Linux 2

Matrix products: default
BLAS:   /igm/apps/R/R-4.1.1_install/lib64/R/lib/libRblas.so
LAPACK: /igm/apps/R/R-4.1.1_install/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.1 tools_4.1.1

**Comment by DavisVaughan** [comment]
Interesting, can you please post the _full_ output from installing clock then? Everything from `install.packages("clock")` to the very end, it might give me more information.

**Comment by james74901** [comment]
> install.packages("clock")
--- Please select a CRAN mirror for use in this session ---
Secure CRAN mirrors 

 1: 0-Cloud [https]
 2: Australia (Canberra) [https]
 3: Australia (Melbourne 1) [https]
 4: Australia (Melbourne 2) [https]
 5: Australia (Perth) [https]
 6: Austria [https]
 7: Belgium (Brussels) [https]
 8: Brazil (PR) [https]
 9: Brazil (RJ) [https]
10: Brazil (SP 1) [https]
11: Brazil (SP 2) [https]
12: Bulgaria [https]
13: Canada (MB) [https]
14: Canada (ON) [https]
15: Chile (Santiago) [https]
16: China (Beijing 2) [https]
17: China (Beijing 3) [https]
18: China (Hefei) [https]
19: China (Hong Kong) [https]
20: China (Guangzhou) [https]
21: China (Jinan) [https]
22: China (Lanzhou) [https]
23: China (Nanjing) [https]
24: China (Shanghai 2) [https]
25: China (Shenzhen) [https]
26: Colombia (Cali) [https]
27: Costa Rica [https]
28: Czech Republic [https]
29: Denmark [https]
30: East Asia [https]
31: Ecuador (Cuenca) [https]
32: France (Lyon 1) [https]
33: France (Lyon 2) [https]
34: France (Marseille) [https]
35: France (Paris 1) [https]
36: Germany (Erlangen) [https]
37: Germany (Leipzig) [https]
38: Germany (Göttingen) [https]
39: Germany (Münster) [https]
40: Germany (Regensburg) [https]
41: Greece [https]
42: Hungary [https]
43: Iceland [https]
44: India (Bengaluru) [https]
45: India (Bhubaneswar) [https]
46: Indonesia (Banda Aceh) [https]
47: Iran (Mashhad) [https]
48: Italy (Milano) [https]
49: Italy (Padua) [https]
50: Japan (Tokyo) [https]
51: Japan (Yonezawa) [https]
52: Korea (Gyeongsan-si) [https]
53: Malaysia [https]
54: Mexico (Mexico City) [https]
55: Mexico (Texcoco) [https]
56: Morocco [https]
57: Netherlands (Dronten) [https]
58: New Zealand [https]
59: Norway [https]
60: South Africa (Johannesburg) [https]
61: Spain (A Coruña) [https]
62: Spain (Madrid) [https]
63: Sweden (Umeå) [https]
64: Switzerland (Zurich 1) [https]
65: Taiwan (Taipei) [https]
66: Turkey (Denizli) [https]
67: Turkey (Istanbul) [https]
68: Turkey (Mersin) [https]
69: UK (Bristol) [https]
70: UK (London 1) [https]
71: USA (IA) [https]
72: USA (MI) [https]
73: USA (MO) [https]
74: USA (OH) [https]
75: USA (OR) [https]
76: USA (TN) [https]
77: United Arab Emirates [https]
78: Uruguay [https]
79: (other mirrors)

Selection: 74
trying URL 'https://cran.case.edu/src/contrib/clock_0.6.1.tar.gz'
Content type 'application/x-gzip' length 501028 bytes (489 KB)
==================================================
downloaded 489 KB

* installing *source* package ‘clock’ ...
** package ‘clock’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c cpp11.cpp -o cpp11.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c duration.cpp -o duration.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c enums.cpp -o enums.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c format.cpp -o format.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c gregorian-year-day.cpp -o gregorian-year-day.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c gregorian-year-month-day.cpp -o gregorian-year-month-day.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c gregorian-year-month-weekday.cpp -o gregorian-year-month-weekday.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c iso-year-week-day.cpp -o iso-year-week-day.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c naive-time.cpp -o naive-time.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c quarterly-year-quarter-day.cpp -o quarterly-year-quarter-day.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c rcrd.cpp -o rcrd.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c sys-time.cpp -o sys-time.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c time-point.cpp -o time-point.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c utils.cpp -o utils.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c weekday.cpp -o weekday.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c zone.cpp -o zone.o
g++ -std=gnu++11 -I"/igm/apps/R/R-4.1.1_install/lib64/R/include" -DNDEBUG  -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/cpp11/include' -I'/igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/include' -I/usr/local/include   -fpic  -g -O2  -c zoned-time.cpp -o zoned-time.o
g++ -std=gnu++11 -shared -L/igm/apps/R/R-4.1.1_install/lib64/R/lib -L/usr/local/lib64 -o clock.so cpp11.o duration.o enums.o format.o gregorian-year-day.o gregorian-year-month-day.o gregorian-year-month-weekday.o iso-year-week-day.o naive-time.o quarterly-year-quarter-day.o rcrd.o sys-time.o time-point.o utils.o weekday.o zone.o zoned-time.o -L/igm/apps/R/R-4.1.1_install/lib64/R/lib -lR
installing to /igm/apps/R/R-4.1.1_install/lib64/R/library/00LOCK-clock/00new/clock/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘clock’:
 .onLoad failed in loadNamespace() for 'clock', details:
  call: zone_validate(zone)
  error: 'UTC' is not a known time zone.
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/igm/apps/R/R-4.1.1_install/lib64/R/library/clock’

The downloaded source packages are in
        ‘/igm/temp/RtmpDnz6y7/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("clock") :
  installation of package ‘clock’ had non-zero exit status

**Comment by DavisVaughan** [comment]
`Running under: Amazon Linux 2` - are you using a VM through Amazon? Anything you can provide about your setup would be helpful

**Comment by james74901** [comment]
Yep, the OS is AL2 & it's an EC2 (AWS) instance.

Linux host.org 5.10.162-141.675.amzn2.x86_64 #1 SMP Mon Jan 9 22:45:11 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by DavisVaughan** [comment]
Interestingly I was able to build just fine on the AL2 EC2 instance

```
Linux ip-172-31-29-82.ec2.internal 5.10.177-158.645.amzn2.x86_64 #1 SMP Thu Apr 6 16:53:11 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

It looks like we are basically using the same version (mine is `5.10.177-158.645` yours is `5.10.162-141.675`, which seems close?). So I'm not really sure what is happening.

I installed R with

```
sudo amazon-linux-extras install R4
```

and that gave me R 4.0.2

```r
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-koji-linux-gnu (64-bit)
Running under: Amazon Linux 2

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
```

did you do something else?

```
* installing *source* package ‘clock’ ...
** package ‘clock’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c cpp11.cpp -o cpp11.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c duration.cpp -o duration.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c enums.cpp -o enums.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c format.cpp -o format.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c gregorian-year-day.cpp -o gregorian-year-day.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c gregorian-year-month-day.cpp -o gregorian-year-month-day.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c gregorian-year-month-weekday.cpp -o gregorian-year-month-weekday.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c iso-year-week-day.cpp -o iso-year-week-day.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c naive-time.cpp -o naive-time.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c quarterly-year-quarter-day.cpp -o quarterly-year-quarter-day.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c rcrd.cpp -o rcrd.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c sys-time.cpp -o sys-time.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c time-point.cpp -o time-point.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c utils.cpp -o utils.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c weekday.cpp -o weekday.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c zone.cpp -o zone.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/cpp11/include' -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/tzdb/include' -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c zoned-time.cpp -o zoned-time.o
g++ -m64 -std=gnu++11 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o clock.so cpp11.o duration.o enums.o format.o gregorian-year-day.o gregorian-year-month-day.o gregorian-year-month-weekday.o iso-year-week-day.o naive-time.o quarterly-year-quarter-day.o rcrd.o sys-time.o time-point.o utils.o weekday.o zone.o zoned-time.o -L/usr/lib64/R/lib -lR
installing to /home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/00LOCK-clock/00new/clock/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘clock’
    finding HTML links ... done
    Date-arithmetic                         html  
    Date-getters                            html  
    Date-setters                            html  
    as-zoned-time-Date                      html  
    as-zoned-time-naive-time                html  
    as-zoned-time-posixt                    html  
    as-zoned-time-sys-time                  html  
    as_date                                 html  
    as_date_time                            html  
    as_duration                             html  
    as_iso_year_week_day                    html  
    as_naive_time                           html  
    as_sys_time                             html  
    as_weekday                              html  
    as_year_day                             html  
    as_year_month_day                       html  
    as_year_month_weekday                   html  
    as_year_quarter_day                     html  
    as_zoned_time                           html  
    calendar-boundary                       html  
    calendar-count-between                  html  
    calendar_group                          html  
    calendar_leap_year                      html  
    calendar_month_factor                   html  
    calendar_narrow                         html  
    calendar_precision                      html  
    calendar_widen                          html  
    clock-arith                             html  
    clock-arithmetic                        html  
    clock-codes                             html  
    clock-getters                           html  
    clock-invalid                           html  
    clock-package                           html  
    clock-setters                           html  
    clock_labels                            html  
    clock_locale                            html  
    date-and-date-time-boundary             html  
    date-and-date-time-rounding             html  
    date-and-date-time-shifting             html  
    date-boundary                           html  
    date-count-between                      html  
    date-formatting                         html  
    date-group                              html  
    date-rounding                           html  
    date-sequence                           html  
    date-shifting                           html  
    date-time-parse                         html  
    date-today                              html  
    date-zone                               html  
    date_build                              html  
    date_count_between                      html  
    date_format                             html  
    date_group                              html  
    date_leap_year                          html  
    date_month_factor                       html  
    date_parse                              html  
    date_seq                                html  
    date_time_build                         html  
    date_weekday_factor                     html  
    duration-arithmetic                     html  
    duration-helper                         html  
    duration-rounding                       html  
    duration_cast                           html  
    duration_precision                      html  
    format.clock_zoned_time                 html  
    is_duration                             html  
    is_iso_year_week_day                    html  
    is_naive_time                           html  
    is_sys_time                             html  
    is_weekday                              html  
    is_year_day                             html  
    is_year_month_day                       html  
    is_year_month_weekday                   html  
    is_year_quarter_day                     html  
    is_zoned_time                           html  
    iso-year-week-day-arithmetic            html  
    iso-year-week-day-boundary              html  
    iso-year-week-day-count-between         html  
    iso-year-week-day-getters               html  
    iso-year-week-day-group                 html  
    iso-year-week-day-narrow                html  
    iso-year-week-day-setters               html  
    iso-year-week-day-widen                 html  
    iso_year_week_day                       html  
    naive_time_info                         html  
    naive_time_parse                        html  
    posixt-arithmetic                       html  
    posixt-boundary                         html  
    posixt-count-between                    html  
    posixt-formatting                       html  
    posixt-getters                          html  
    posixt-group                            html  
    posixt-rounding                         html  
    posixt-sequence                         html  
    posixt-setters                          html  
    posixt-shifting                         html  
    reexports                               html  
    seq.clock_duration                      html  
    seq.clock_iso_year_week_day             html  
    seq.clock_time_point                    html  
    seq.clock_year_day                      html  
    seq.clock_year_month_day                html  
    seq.clock_year_month_weekday            html  
    seq.clock_year_quarter_day              html  
    sys-parsing                             html  
    sys_time_info                           html  
    sys_time_now                            html  
    time-point-arithmetic                   html  
    time-point-rounding                     html  
    time_point_cast                         html  
    time_point_count_between                html  
    time_point_precision                    html  
    time_point_shift                        html  
    weekday-arithmetic                      html  
    weekday                                 html  
    weekday_code                            html  
    weekday_factor                          html  
    year-day-arithmetic                     html  
    year-day-boundary                       html  
    year-day-count-between                  html  
    year-day-getters                        html  
    year-day-group                          html  
    year-day-narrow                         html  
    year-day-setters                        html  
    year-day-widen                          html  
    year-month-day-arithmetic               html  
    year-month-day-boundary                 html  
    year-month-day-count-between            html  
    year-month-day-getters                  html  
    year-month-day-group                    html  
    year-month-day-narrow                   html  
    year-month-day-setters                  html  
    year-month-day-widen                    html  
    year-month-weekday-arithmetic           html  
    year-month-weekday-boundary             html  
    year-month-weekday-count-between        html  
    year-month-weekday-getters              html  
    year-month-weekday-group                html  
    year-month-weekday-narrow               html  
    year-month-weekday-setters              html  
    year-month-weekday-widen                html  
    year-quarter-day-arithmetic             html  
    year-quarter-day-boundary               html  
    year-quarter-day-count-between          html  
    year-quarter-day-getters                html  
    year-quarter-day-group                  html  
    year-quarter-day-narrow                 html  
    year-quarter-day-setters                html  
    year-quarter-day-widen                  html  
    year_day                                html  
    year_month_day                          html  
    year_month_day_parse                    html  
    year_month_weekday                      html  
    year_quarter_day                        html  
    zoned-parsing                           html  
    zoned-zone                              html  
    zoned_time_now                          html  
    zoned_time_precision                    html  
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (clock)

The downloaded source packages are in
        ‘/tmp/RtmpQ182db/downloaded_packages’
> library(clock)
> date_time_build(2019, zone = "UTC")
[1] "2019-01-01 UTC"
```

**Comment by DavisVaughan** [comment]
What does `packageDescription("tzdb")` give you?

**Comment by james74901** [comment]
> packageDescription("tzdb")
Package: tzdb
Title: Time Zone Database Information
Version: 0.3.0
Authors@R: c( person("Davis", "Vaughan", , "davis@rstudio.com", role =
        c("aut", "cre")), person("Howard", "Hinnant", role = "cph",
        comment = "Author of the included date library"),
        person("RStudio", role = c("cph", "fnd")) )
Description: Provides an up-to-date copy of the Internet Assigned
        Numbers Authority (IANA) Time Zone Database. It is updated
        periodically to reflect changes made by political bodies to
        time zone boundaries, UTC offsets, and daylight saving time
        rules. Additionally, this package provides a C++ interface for
        working with the 'date' library. 'date' provides comprehensive
        support for working with dates and date-times, which this
        package exposes to make it easier for other R packages to
        utilize. Headers are provided for calendar specific
        calculations, along with a limited interface for time zone
        manipulations.
License: MIT + file LICENSE
URL: https://tzdb.r-lib.org, https://github.com/r-lib/tzdb
BugReports: https://github.com/r-lib/tzdb/issues
Depends: R (>= 3.4.0)
Suggests: covr, testthat (>= 3.0.0)
LinkingTo: cpp11 (>= 0.4.2)
Biarch: yes
Config/Needs/website: tidyverse/tidytemplate
Config/testthat/edition: 3
Encoding: UTF-8
RoxygenNote: 7.1.2
SystemRequirements: C++11
NeedsCompilation: yes
Packaged: 2022-03-28 13:59:28 UTC; davis
Author: Davis Vaughan [aut, cre], Howard Hinnant [cph] (Author of the
        included date library), RStudio [cph, fnd]
Maintainer: Davis Vaughan <davis@rstudio.com>
Repository: CRAN
Date/Publication: 2022-03-28 15:00:02 UTC
Built: R 4.1.1; x86_64-pc-linux-gnu; 2022-05-10 16:44:53 UTC; unix

-- File: /igm/apps/R/R-4.1.1_install/lib64/R/library/tzdb/Meta/package.rds

**Comment by DavisVaughan** [comment]
I'm not really sure what to do here

The only other think I might suggest is `install.packages("tzdb")` then a restart of R, then `install.packages("clock")` to ensure that tzdb is rebuilt with the exact same version of the compiler that clock is.

Did you happen to do a system update recently?

**Comment by DavisVaughan** [comment]
Does vroom work for you? It also uses the time zone database in tzdb. Try:

```r
vroom::vroom(I("x\n2019-01-01 00:00:00\n"), locale = vroom::locale(tz = "America/New_York"), delim = ",")$x
```

**Comment by james74901** [comment]
Ha, I did the `install.packages("tzdb")`, restarted R, and then `install.packages("clock")` seems to have worked fine. No idea what the issue was, but the re-install of tzdb seems to have things working! Thanks for the help and for the super quick response!

**Comment by DavisVaughan** [comment]
Nice, I imagine that your old version of tzdb was compiled with a version of gcc that is different enough from whatever version of gcc you have now that it caused some kind of conflicts when clock tried to link to it. That explains why `tzdb::tzdb_names()` worked but clock didn't.

**Comment by james74901** [comment]
That makes sense. We actually used to run centos and have recently switched to AL2. It's quite possible that tzdb was compiled and installed under the old centos system and that caused the issue when running on the new AL2.

**Comment by DavisVaughan** [comment]
That would do it!

**Comment by DavisVaughan** [comment]
(In that case you really should purge your entire R library and reinstall all of it, otherwise you'll probably have similar issues elsewhere)
