### ISSUE TITLE
Commands time_point_ceiling or round are having no effect after time_point_floor is used maybe?

### ISSUE THREAD

**Issue by clairerichardsRN** [r-lib/clock#342]
It's probably an outside use case due to how I'm processing my data but I've had to round down and then round back up the same variable and it appears that rounding back up won't work...

Here is just one clock time point
`dput(test)
structure(list(ticks = 17682L), class = c("clock_naive_time", 
"clock_time_point", "clock_rcrd", "vctrs_rcrd", "vctrs_vctr"), precision = 4L, clock = 1L)`
time_point_ceiling and round have no change on it.
```
 test
<clock_naive_time[1]>
[1] "2018-05-31"
time_point_ceiling(test, "day", n=1)
<clock_naive_time[1]>
[1] "2018-05-31"
```

Whereas this other one works as expected
```
`structure(list(ticks = 17683L, ticks_of_day = 26147L), class = c("clock_naive_time", 
"clock_time_point", "clock_rcrd", "vctrs_rcrd", "vctrs_vctr"), clock = 1L, precision = 7L)
```
```
> testb
<clock_naive_time[1]>
[1] "2018-06-01T07:15:47"
> time_point_ceiling(testb, "day", n=1)
<clock_naive_time[1]>
[1] "2018-06-02"
```
`

**Comment by DavisVaughan** [comment]
I can explain in more detail on Monday but basically this is mathematically correct behavior. I explain it in detail here https://clock.r-lib.org/reference/time-point-rounding.html#boundary-handling, particularly the last sentence of 

> Notice that, regardless of whether you are doing a floor or ceiling, if the input falls on a boundary then it will be returned as is.
