### ISSUE TITLE
`date_time_parse_RFC_3339()` not working with milliseconds

### ISSUE THREAD

**Issue by m-muecke** [r-lib/clock#377]
I'm trying to parse a RFC 3339 format with milliseconds precision, but doesn't seem to be parse or is it just not supported?

``` r
x <- "2024-10-29T12:34:56.789+02:00"
clock::date_time_parse_RFC_3339(x, offset = "%Ez")
#> Warning: Failed to parse 1 string at location 1. Returning `NA` at that
#> location.
#> [1] NA
```

<sup>Created on 2024-10-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
When parsing straight into POSIXct, the precision is locked as `"second"` so you can't parse milliseconds.

You have to parse into an actual clock time that supports milliseconds instead, in this case, the underlying helper for RFC 3339 parses into sys-time.

``` r
x <- "2024-10-29T12:34:56.789+02:00"

x <- clock::sys_time_parse_RFC_3339(
  x,
  offset = "%Ez", 
  precision = "millisecond"
)

# here we have the milliseconds
x
#> <sys_time<millisecond>[1]>
#> [1] "2024-10-29T10:34:56.789"

# we lose them on conversion to POSIXct, because it can only
# holistically support seconds
as.POSIXct(x)
#> [1] "2024-10-29 06:34:56 EDT"

# see how we dont have them as we convert back
clock::as_sys_time(as.POSIXct(x))
#> <sys_time<second>[1]>
#> [1] "2024-10-29T10:34:56"
```

If you can do all the manipulations with the sys-time vector, that's great. If you have to convert back to POSIXct, you will lose the milliseconds.

The way POSIXct is implemented makes it ill suited for fractional times, I think this gives a good explanation of why:
https://clock.r-lib.org/articles/faq.html#where-did-my-posixct-subseconds-go
